apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: julianpi2003/bff-image:latest  # Incluye el nombre de usuario aquí
        ports:
          - containerPort: 5000
