name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Se activa en cada commit a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out the code
        uses: actions/checkout@v2

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir y subir la imagen Docker del frontend
      - name: Build and push frontend Docker image
        run: |
          docker build -t julianpi2003/frontend-image:latest -f Front/s-repo/Dockerfile Front/s-repo
          docker push julianpi2003/frontend-image:latest

      # Paso 4: Construir y subir la imagen Docker del BFF
      - name: Build and push BFF Docker image
        run: |
          docker build -t julianpi2003/bff-image:latest -f Back/Dockerfile Back
          docker push julianpi2003/bff-image:latest

      # Paso 5: Configurar `kubectl`
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3  # Usar la versión v3
        with:
          version: 'latest'

      # Paso 6: Configurar `kubeconfig` usando el secreto en GitHub
      - name: Configure kubectl to connect to the cluster
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "${KUBECONFIG}" | base64 --decode > $HOME/.kube/config

      # Paso 7: Aplicar los manifiestos de Kubernetes
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/bff-deployment.yaml
